# Generated by Django 6.0.6 on 2026-06-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_extractedclause_riskflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extract_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
